// AUTO-GENERATED by scripts/generateEnvironmentAssetManifest.mjs
// Do not edit by hand - regenerate by running:
//   node scripts/generateEnvironmentAssetManifest.mjs
// from the frontend/ directory. Regenerated automatically on every
// pnpm dev / pnpm build via the predev/prebuild hooks.
//
// Scale is computed from each asset's TRUE rendered bounding box (via
// the real GLTFLoader + Box3, matching exactly how the running app
// loads these files) - not raw vertex accessor bounds, which ignore
// node transform matrices and were found to be wrong by 100x or more
// for multiple assets in this project.

export interface DiscoveredEnvironmentProp {
  readonly assetId: string;
  readonly category: string;
  readonly url: string;
  readonly baseScale: number;
}

export const DISCOVERED_ENVIRONMENT_PROPS: readonly DiscoveredEnvironmentProp[] = [
  {
    assetId: "models:environment:bush",
    category: "bush",
    url: "/models/environment/Bushes/Bushe_02.glb",
    // Auto-discovered: smallest file in "Bushes/" (0.9 MB).
    // Other candidates found in this folder: Bushe_02.glb (0.9 MB), Bushe_01.glb (2.6 MB)
    // TRUE rendered height (real GLTFLoader + Box3, not raw accessor bounds): 380.51761 units.
    baseScale: 0.0031535991391772344,
  },
  {
    assetId: "models:environment:flower",
    category: "flower",
    url: "/models/environment/Flowers/Flower_White.glb",
    // Auto-discovered: smallest file in "Flowers/" (1.0 MB).
    // Other candidates found in this folder: Flower_White.glb (1.0 MB)
    // TRUE rendered height (real GLTFLoader + Box3, not raw accessor bounds): 2250.64014 units.
    baseScale: 0.0001332954101372758,
  },
  {
    assetId: "models:environment:grass",
    category: "grass",
    url: "/models/environment/Grass/Grass_01.glb",
    // Auto-discovered: smallest file in "Grass/" (4.0 MB).
    // Other candidates found in this folder: Grass_01.glb (4.0 MB)
    // TRUE rendered height (real GLTFLoader + Box3, not raw accessor bounds): 0.04771 units.
    baseScale: 7.335974911438046,
  },
  {
    assetId: "models:environment:rock",
    category: "rock",
    url: "/models/environment/Rocks/Rock_03.glb",
    // Auto-discovered: smallest file in "Rocks/" (0.0 MB).
    // Other candidates found in this folder: Rock_03.glb (0.0 MB), Rock_02.glb (0.2 MB), Rock_01.glb (4.0 MB)
    // TRUE rendered height (real GLTFLoader + Box3, not raw accessor bounds): 1.63646 units.
    baseScale: 0.7332917128022252,
  },
  {
    assetId: "models:environment:tree",
    category: "tree",
    url: "/models/environment/Trees/Three_02.glb",
    // Auto-discovered: smallest file in "Trees/" (4.3 MB).
    // Other candidates found in this folder: Three_02.glb (4.3 MB), Three_01.glb (8.5 MB)
    // TRUE rendered height (real GLTFLoader + Box3, not raw accessor bounds): 16.87827 units.
    baseScale: 0.2962388086191334,
  },
];
