export enum QuestObjectiveType {
  TALK = "TALK",
  COLLECT = "COLLECT",
  EXPLORE = "EXPLORE",
  READ_SCRIPTURE = "READ_SCRIPTURE",
  REACH_LOCATION = "REACH_LOCATION",
  USE_OBJECT = "USE_OBJECT",
  MULTI_STEP = "MULTI_STEP",
}
