export interface BibleBookName {
  readonly name: string;
  readonly testament: "OLD" | "NEW";
}

export const BIBLE_BOOK_NAMES: readonly BibleBookName[] = [
  { name: "Genesis", testament: "OLD" },
  { name: "Exodus", testament: "OLD" },
  { name: "Leviticus", testament: "OLD" },
  { name: "Numbers", testament: "OLD" },
  { name: "Deuteronomy", testament: "OLD" },
  { name: "Joshua", testament: "OLD" },
  { name: "Judges", testament: "OLD" },
  { name: "Ruth", testament: "OLD" },
  { name: "1 Samuel", testament: "OLD" },
  { name: "2 Samuel", testament: "OLD" },
  { name: "1 Kings", testament: "OLD" },
  { name: "2 Kings", testament: "OLD" },
  { name: "1 Chronicles", testament: "OLD" },
  { name: "2 Chronicles", testament: "OLD" },
  { name: "Ezra", testament: "OLD" },
  { name: "Nehemiah", testament: "OLD" },
  { name: "Esther", testament: "OLD" },
  { name: "Job", testament: "OLD" },
  { name: "Psalms", testament: "OLD" },
  { name: "Proverbs", testament: "OLD" },
  { name: "Ecclesiastes", testament: "OLD" },
  { name: "Song of Solomon", testament: "OLD" },
  { name: "Isaiah", testament: "OLD" },
  { name: "Jeremiah", testament: "OLD" },
  { name: "Lamentations", testament: "OLD" },
  { name: "Ezekiel", testament: "OLD" },
  { name: "Daniel", testament: "OLD" },
  { name: "Hosea", testament: "OLD" },
  { name: "Joel", testament: "OLD" },
  { name: "Amos", testament: "OLD" },
  { name: "Obadiah", testament: "OLD" },
  { name: "Jonah", testament: "OLD" },
  { name: "Micah", testament: "OLD" },
  { name: "Nahum", testament: "OLD" },
  { name: "Habakkuk", testament: "OLD" },
  { name: "Zephaniah", testament: "OLD" },
  { name: "Haggai", testament: "OLD" },
  { name: "Zechariah", testament: "OLD" },
  { name: "Malachi", testament: "OLD" },
  { name: "Matthew", testament: "NEW" },
  { name: "Mark", testament: "NEW" },
  { name: "Luke", testament: "NEW" },
  { name: "John", testament: "NEW" },
  { name: "Acts", testament: "NEW" },
  { name: "Romans", testament: "NEW" },
  { name: "1 Corinthians", testament: "NEW" },
  { name: "2 Corinthians", testament: "NEW" },
  { name: "Galatians", testament: "NEW" },
  { name: "Ephesians", testament: "NEW" },
  { name: "Philippians", testament: "NEW" },
  { name: "Colossians", testament: "NEW" },
  { name: "1 Thessalonians", testament: "NEW" },
  { name: "2 Thessalonians", testament: "NEW" },
  { name: "1 Timothy", testament: "NEW" },
  { name: "2 Timothy", testament: "NEW" },
  { name: "Titus", testament: "NEW" },
  { name: "Philemon", testament: "NEW" },
  { name: "Hebrews", testament: "NEW" },
  { name: "James", testament: "NEW" },
  { name: "1 Peter", testament: "NEW" },
  { name: "2 Peter", testament: "NEW" },
  { name: "1 John", testament: "NEW" },
  { name: "2 John", testament: "NEW" },
  { name: "3 John", testament: "NEW" },
  { name: "Jude", testament: "NEW" },
  { name: "Revelation", testament: "NEW" },
];
